### ISSUE TITLE
error in getHeader()

### ISSUE THREAD

**Issue by lidaof** [GMOD/bam-js#26]
Hi Colin,

Trying use the getHeader() function but get following error:
![image](https://user-images.githubusercontent.com/102806/57041347-9b81a500-6c27-11e9-8f9e-a77435d9a1d4.png)

my code is like:

```
this.bam = new BamFile({
            bamUrl: url,
            baiUrl: url + '.bai',
        });

const header = await this.bam.getHeader();
        console.log(header);
```

can you suggest how to fix this? Thanks.

**Comment by cmdcolin** [comment]
I can reproduce this. I think I have a fix and will release a new version shortly, just need to make sure to test!

**Comment by cmdcolin** [comment]
@lidaof Ok I have made two changes that should fix this, mostly with regards to compatibility with the browser's native fetch. If you want to try updating to @gmod/bam@1.0.18 to give it a shot that would be great!

**Comment by lidaof** [comment]
hi @cmdcolin thanks for fast fix, i can confirm if it's bamUrl, it's fixed. if use a bamPath, a new error raised :)

![image](https://user-images.githubusercontent.com/102806/57055525-a527fe80-6c61-11e9-8cc2-ce373d940b54.png)

**Comment by cmdcolin** [comment]
I think you can't use bamPath in the browser as that tries to access the filesystem directly via node.js file system calls and this does not exist in the browser.

If you want to access for example a file that a user opened in the browser, you might want to use the BlobFile class in https://github.com/GMOD/generic-filehandle and pass it to the bamFilehandle/baiFilehandle argument. The bamPath/bamUrl are just convenience methods for using the generic-filehandle class directly

**Comment by cmdcolin** [comment]
Note that some of your earlier comments about this topic of opening files easily actually motivated the creation of generic-filehandle so I hope it is useful :) feel free to provide feedback

**Comment by cmdcolin** [comment]
It's designed hopefully to be usable across multiple modules such as cram-js, bam-js, bbi-js, tabix-js, etc.

**Comment by lidaof** [comment]
oh...yeah..stupid me....what i was thinking using local path in browser....sorry!
Thank you!! @cmdcolin
