### ISSUE TITLE
question on seq_id of returned feature

### ISSUE THREAD

**Issue by lidaof** [GMOD/bam-js#27]
Hi Colin,

I am curious about the seq_id in the returned BamRecord.

in the screenshot below you can see I got BamRecord has seq_id as 6
![image](https://user-images.githubusercontent.com/102806/57056511-a4df3180-6c68-11e9-92e3-74d2888e8e59.png)

but in the header the 6 is chr6, the read should be in chr7 as i am querying a region in chr7
![image](https://user-images.githubusercontent.com/102806/57056562-ed96ea80-6c68-11e9-9a31-7839aea3bc8c.png)

do I need to add 1 to the seq_id to get right chr? Thanks.

by the way, why the seq property is undefined? there should be read sequence. Thank you.

**Comment by cmdcolin** [comment]
The indexToChr property might help (in your coffee you can see it is the sixth SQ line the first line was not SQ) https://github.com/GMOD/bam-js/blob/master/test/bai.test.js#L66

Also try getReadBases ttps://github.com/GMOD/bam-js/blob/master/test/bai.test.js#L10

I may try to redesign the record class to make it easier to accomplish these tasks as it is a bit opaque right now but if you look at the test code you can see some example usage

**Comment by lidaof** [comment]
Hi @cmdcolin , this is very clear after your answer :)
I should check the test folder earlier :)
Thank you!
