### ISSUE TITLE
error with local uploaded file

### ISSUE THREAD

**Issue by lidaof** [GMOD/bam-js#31]
Hi Colin,

I am using latest version from npm, I am uploading both the bam and .bai to a file input and construct bamFile with both File object, from console.log I can see bamFile constructed successfully, but get error afterwards. Could you please take a look? Here are the [test code](https://gist.github.com/lidaof/0d9a4a95decc74ce972b3883702a8426), and [test bam file](https://wangftp.wustl.edu/~dli/test/a.bam), [index file](https://wangftp.wustl.edu/~dli/test/a.bam.bai). Thanks.

![image](https://user-images.githubusercontent.com/102806/59223238-0e6c2d00-8b91-11e9-9c1e-04646fcb5b8b.png)

**Comment by lidaof** [comment]
If I commented out the getHeader() function, the error will gone...
while I could not get any data in the region which should have some data :)
```
const records = await bam.getRecordsForRange('chr1',3001563,3006715);
console.log(records);
```

records is empty...

**Comment by cmdcolin** [comment]
I recommend using generic-filehandle from https://github.com/GMOD/generic-filehandle

Then you can just use the BlobFile class like this, I tested it in a local environment with your same setup :)

```
import React, { Component } from 'react';
import './App.css';
import { BamFile } from '@gmod/bam';
import { BlobFile } from 'generic-filehandle'

class App extends Component {

  handleFileUpload = async (event) => {
    const fileList = Array.from(event.target.files);
    const baiFilehandle = new BlobFile(fileList.filter(f => f.name.endsWith('.bai'))[0]);
    const bamFilehandle = new BlobFile(fileList.filter(f => !f.name.endsWith('.bai'))[0]);
    const bam = new BamFile({
        bamFilehandle,
        baiFilehandle,
    });
    const header = await bam.getHeader();
    console.log(header);
    const records = await bam.getRecordsForRange('chr1',10423,10755);
    console.log(records);
  }
  render() {

    return (
      <div className="App">
        <input type="file" id="trackFile" multiple onChange={this.handleFileUpload} />
      </div>
    );
  }
}

export default App;
```

Please use generic-filehandle > version 2.0.0 on the latest @gmod/bam

**Comment by cmdcolin** [comment]
Note that if I inspect your bam file the chr1 records don't really start until after 3,000,000 bp or so so try

`const records = await bam.getRecordsForRange('chr1',0,3900000);`

**Comment by lidaof** [comment]
I see...thank you Colin @cmdcolin 
I was think the Blob was already take care of in BamFile constructor :) my bad..

thanks again
