### ISSUE TITLE
All tags are stored in lower case, but technically lower case tags are distinct from upper case

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/bam-js#62]

**Comment by cmdcolin** [comment]
fixed in v3.0.0

**Comment by alexpreynolds** [comment]
Hello, is there a particular commit that contains support for lowercase tags? I'm running into records that contain both `AS` and local `as` tags, but am running a fork that is a little older. Thanks for any pointers.

**Comment by cmdcolin** [comment]
I did a big refactoring to introduce this change in @gmod/bam v3.0.0 which introduced a new way of accessing the "record class", which completely removed the "record.get('tagnamehere')" function and changed it to be all "getters" so you have

```
record.start // number
record.end // number
record.name // string
record.tags // all the tags stored as a "plain old javascript object" e.g. Record<string,unknown>, and it is case sensitive so you can have both upper and lower case tag names
record.tags.AS // your tag, string or something
record.tags.as // your tag, string or something
```

Note: @gmod/bam@v3.0.0 uses generic-filehandle but  @gmod/bam@v5.0.0 (published today) converted from generic-filehandle to generic-filehandle2 https://github.com/GMOD/generic-filehandle2 (it is pretty similar to generic-filehandle but does not require the Buffer polyfill in the browser)
