### ISSUE TITLE
Feature sequence is undefined

### ISSUE THREAD

**Issue by alexander-veit** [GMOD/bam-js#66]
I am using `getRecordsForRange` to extract data from a BAM file. I can successfully retrieve `feature.get('MD')` and `feature.get('cigar')`, but `feature.get('seq')` is undefined. I am using the latest version. With `samtools view` I can see the sequence. Any help is appreciated. Thanks!

**Comment by cmdcolin** [comment]
@alexander-veit thanks for catching this, was definitely not working with feature.get('seq')

what does work is using feature.getReadBases() in your current version

A new version is now published that allows feature.get('seq')

**Comment by alexander-veit** [comment]
Thanks a lot for the quick fix and the new release! It is working now. Thanks again.
