### ISSUE TITLE
LocalFile is not a constructor

### ISSUE THREAD

**Issue by amijalis** [GMOD/bam-js#93]
Hello!

I am developing an application with node v18.9.0 and webpack v5.74.0. When I try to parse a new Bamfile with the code

`const t = new BamFile({ bamPath: "../test_alignment.bam" });`

I get an error

`Uncaught TypeError: generic_filehandle__WEBPACK_IMPORTED_MODULE_3__.LocalFile is not a constructor`

Is there something basic that I am missing? Thanks for your help!

**Comment by cmdcolin** [comment]
are you running the app under node.js or in the browser? 

the bamPath only works with local file systems e.g. under nodejs. if you are using in the browser, then the "bamFilehandle" arugment should be used, with a RemoteFile handle

example:

```
const {RemoteFile} = require('generic-filehandle')
const bam = new BamFile({
  bamFilehandle: new RemoteFile('yourfile.bam'), // or a full http url
  baiFilehandle: new RemoteFile('yourfile.bam.bai') // or a full http url
})
```
I can try to add this example to the readme

**Comment by amijalis** [comment]
Okay, that makes sense. I am indeed running the app in the browser and this worked. Thanks for the code example!
