### ISSUE TITLE
Typing issues 

### ISSUE THREAD

**Issue by tuner** [GMOD/bam-js#97]
Hi,

I'm trying to validate types (I'm using TS through JSDoc) in my codebase using `tsc`, but I stumbled upon a couple of issues in `@GMOD/bam@1.1.18`.

The first one:

```
../../node_modules/@gmod/bam/dist/util.d.ts:4:44 - error TS2304: Cannot find name 'Long'.

4 export declare function longToNumber(long: Long): number;
                                             ~~~~
```

There's no `"long"` package imported in `util.d.ts` (https://cdn.jsdelivr.net/npm/@gmod/bam@1.1.18/dist/util.d.ts), although it's in the original source file: https://github.com/GMOD/bam-js/blob/492c145a3a714d898b3a38f82030876900ad7ede/src/util.ts#L1

🤷

If I checkout `v1.1.18` of this repo and compile the project, the long import is missing from `util.d.ts`. If I checkout HEAD and compile, then it's there. Maybe there's some problem in the old `typescript@4.9.4` (?)

And then there's the other issue:

```
../../node_modules/@gmod/bam/dist/htsget.d.ts:14:5 - error TS2416: Property '_readChunk' in type 'HtsgetFile' is not assignable to the same property in base type 'BamFile'.
  Type '(params: { chunk: { buffer: Buffer; chunk: Chunk; }; opts: BaseOpts; }) => Promise<{ data: Buffer; cpositions: null; dpositions: null; chunk: Chunk; }>' is not assignable to type '({ chunk, opts }: { chunk: Chunk; opts: BaseOpts; }) => Promise<{ data: any; cpositions: any; dpositions: any; chunk: Chunk; }>'.
    Types of parameters 'params' and '__0' are incompatible.
      Type '{ chunk: Chunk; opts: BaseOpts; }' is not assignable to type '{ chunk: { buffer: Buffer; chunk: Chunk; }; opts: BaseOpts; }'.
        Types of property 'chunk' are incompatible.
          Type 'Chunk' is missing the following properties from type '{ buffer: Buffer; chunk: Chunk; }': buffer, chunk

14     _readChunk(params: {
       ~~~~~~~~~~
```

Indeed, they are different:
https://github.com/GMOD/bam-js/blob/492c145a3a714d898b3a38f82030876900ad7ede/src/bamFile.ts#L401
https://github.com/GMOD/bam-js/blob/492c145a3a714d898b3a38f82030876900ad7ede/src/htsget.ts#L110

However, I don't have enough knowledge of TypeScript to say whether these should be compatible or not. 🤔

And btw, I'm using `typescript@5.0.4`.

**Comment by cmdcolin** [comment]
Just curious are you using skipLibCheck:true or false?

**Comment by tuner** [comment]
It's on the default setting (true?). It seems that I can get rid of the error message by setting it to true. Is it a good long-term solution?

**Comment by cmdcolin** [comment]
We can likely aim to fix usage of @gmod/bam with skipLibCheck:false (e.g. the default) but I have used skipLibCheck:true in a lot of my projects that consume libraries like @gmod/bam (not ideal, but a quick workaround for stuff like this)

**Comment by cmdcolin** [comment]
i was able to build with skipLibCheck false in a small project (https://github.com/cmdcolin/bam_index_visualizer) 

possibly it is fixed...

**Comment by cmdcolin** [comment]
the particular longToNumber is no longer exported also

**Comment by cmdcolin** [comment]
(optimistically closing, but let me know if it continues to be an issue. ripgrep for Long in the dist folder turns up nothing)
